sudo: required
dist: xenial
services:
- docker
env:
  global:
  - PKGFORGE_STATEFILE=/tmp/pkgforge
  - secure: uUg1WL0tDE1+Q37rVQa8ZZGXlvUz7p2Hwo/VUswXR4RLlv97bGKkbU3EWidEfbO8EUzESA2CGcfjRwo7NssZAGISx+g0ciaLPNn4Uf3pbYz0Ju8ioRD5KqoQUMA+rmMl275ivN22tLWHrn1B0Lh6XeDU6U1ZNv+lB7Ye7FpSZSJM8AA6c7Ozb//BzYuiAi9bSsjGlhzTh23FcQGQpw9RdRw/dhqyeoppI03H2iuCJcY5s+l5tf5ZJhIm7jg5AaT3gjer8cH8KWKh+8UVlFRfK3d9P0StybLCJBqKvtITRDsygbmOdZ68swvM/xhJH5Q5VUOBPOFlgDhvY0MdUr8DXBljblBLjCxCS6t+R91fxDq/I1YJoK8n5AQmDU4iHgCRb3Ssy9k19uMq4711gdwRe4PuHOKdGoiHP8KZ7qJCb/D6pdtz8RMLmsRN6gysP0/7DpORx90BigFNvlKVDFC3MLTNvp7n2h3bXeYBHLBAlHvTGjt7sE6oftA2tGhnZ2dp0/EwiaibvYqgtYFgcBf4BIxqceQckVwqvTmnwtJVlKZVeMqB9WYby8Ds9HxEwNBjIq7yAVSB2KahendNc7SumrPqLusQg0nCyiNYn2jFuuyFAT3vL6HtcAbQ49w3JyWP3wbRhC2Hea513A4KJn3FUGHnBCnS5IHpUDwDebgC/Sw=
script: make
deploy:
  provider: script
  script: make release || travis_terminate 1
  skip_cleanup: true
  on:
    tags: true
notifications:
  email: false
  slack:
    secure: Y/uD97oyBn26Al/eFoNmWucUXupkpks2afV5jh4xaaGiVhJhQdIERkW9+g//oPbCS+ALiJwHZG5BXrrV2bTMJUbz60ddUebnnHqGb7kBnRwDC/YdQOLEbAA/4vTZhI4QXcOm0pWl9Apj062MrBEFtA2pzqSQad4ahoNd75b2HcSrBlLDZ8MOa4KnoTEd5k9mJA4DTsH9NoYUtOhDA3u+mMj2ty5smvpm4Cexr/QlsZJCB8NUtBlpo7Jfs04AkeoFnZiboEnHMzGjgDpH+tl0rfZ9n+cmLNUUbMNV8myINAAvCrgZ1QMW4zGqvydn9clLHB5Zs2Di3p1Gs8JwrezsEfofI7NY7M2zweS05lKVtjGZWs7+Usci/tO7HqjFQMlpUmcS9vvMbueQx5rqEUi/vUY1byul3MdtLmNSiKNNKue/9YU9BLTY7SwIePeOP7e+L6jxKDVjTD/+w+/1OV1yPOq9bu18/OcFJoWr46k+R9NIm7iJkSa7osWF8XdmMzA5i5fzD4Mdn4OtFcXQ07vt2rqu3u6nIZc5q/YKf15JpnzaTFXaNfQatbL1pDrMLHy5zlzTcy5KCBYuXA+Y1tmF+POjaFEmbIMZObehXyeNBbISTLuntR+gdJX6gi/uOVYDE8Ve292mEAadocKiZSoR82e0Qquc+ucN9IrrAeqbX8M=
